### ISSUE TITLE
404 Not found error when trying to download Font Awesome icons

### ISSUE THREAD

**Issue by mountaindude** [Pythonity/icon-font-to-png#10]
icon-font-to-png --download font-awesome

gives me a urllib.error.HTTPError: HTTP Error 404: Not Found

Some URL that has changed over at FA?

**Comment by pawelad** [comment]
Yeah, it probably changed with the release of ~~Bootstrap 4~~ Font Awesome 5.

Thanks for reporting, I'll try to take a look and release a fixed version.

**Comment by Legym** [comment]
I found a temporary solution in case anyone else wants to download FA as images.

1. https://github.com/FortAwesome/Font-Awesome/tree/master/web-fonts-with-css/webfonts
2. Grab the SVG from FA repo and drag them over to http://fontello.com/
3. Highlight and select all the icons and download the webfont
4. Open the downloaded folder and place `fontello.css` and `fontello.ttf` in `icon-font-to-png/bin` (this repo)
5. Run the command `python icon-font-to-png --css fontello.css --ttf fontello.ttf --color '#fd9526' --size 48 ALL`

**Comment by jpzhangvincent** [comment]
Just wondering, has the fix merged yet? I installed with "pip" and still got the error.

**Comment by carlos-reyes** [comment]
Same issue, installed with pip and "command not found" error is still present.

**Comment by Ijustwantyouhappy** [comment]
This module lacks of maintenance, so where is the author?

**Comment by mountaindude** [comment]
Hey guys, this is open source - and as such there typically aren't any solid support commitments. If the module lacks maintenance - feel free to step in and contribute! That's how the really awesome open source projects out there became just that - awesome.

**Comment by HansCronau** [comment]
@mountaindude Thing is: [A PR fixing this issue](https://github.com/Pythonity/icon-font-to-png/pull/12) has been open for almost 3 years. There seem to be some build errors, but there has been no response from the maintainer. Even awesome open source projects need a maintainer to at least accept PRs.
